# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Boinc add-on
version: "0.0.4"
slug: boinc
description: Boinc add-on
url: "https://github.com/hectorespert/hassio-addons/tree/main/boinc"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - addons:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/hectorespert/{arch}-addon-boinc"
apparmor: false
