# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Boinc
version: "1.0.0"
slug: boinc
description: Downloads scientific computing jobs and runs them
url: "https://github.com/hectorespert/boinc-addons/tree/main/boinc"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
options:
  account_manager_url: "https://scienceunited.org"
  account_manager_username: null
  account_manager_password: null
schema:
  account_manager_url: str
  account_manager_username: str
  account_manager_password: password
image: "ghcr.io/hectorespert/{arch}-addon-boinc"
apparmor: false
