# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Boinc
version: "0.4.0"
slug: boinc
description: Downloads scientific computing jobs and runs them
url: "https://github.com/hectorespert/boinc-addons/tree/main/boinc"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
options:
  project: null
  key: null
schema:
  project: url
  key: password
image: "ghcr.io/hectorespert/{arch}-addon-boinc"
apparmor: false
