name: Boinc
version: "1.1.0"
slug: boinc
description: Downloads scientific computing jobs and runs them
url: "https://github.com/hectorespert/boinc-addons/tree/main/boinc"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
ports:
  31416/tcp: null
options:
schema:
  gui_rpc_password: "password?"
  remote_hosts:
    - "str?"
  account_manager_url: "str?"
  account_manager_username: "str?"
  account_manager_password: "password?"
#image: "ghcr.io/hectorespert/{arch}-addon-boinc"
apparmor: false
